### ISSUE TITLE
SQL CLI

### ISSUE THREAD

**Issue by casperhart** [tmontaigu/dbase-rs#55]
Hi, 

I would like to be able to script a report on a dbase dataset entirely in SQL, and output to CSV or parquet without having to write a new rust application for each report.

I really like the look of the datafusion CLI here: https://arrow.apache.org/datafusion/user-guide/cli.html. However it doesn't support custom table providers, so won't work with dbase-rs as far as I can tell. 

Would the implementation of something like this be in scope for this project, or would it be better created as a separate project?

If it is in scope, I wouldn't mind having a go at implementing it, but I'm not sure:
- how best to incorporate it in to the project. E.g. would it be a subfolder (e.g. `./dbase-cli`) with its own `cargo.toml` ?
- Whether it's acceptable to clone the datafusion CLI and add minor changes, or if it's better implemented from scratch.

Happy to discuss, thanks

**Comment by tmontaigu** [comment]
I would say that its probably better to at least start it as a separate project.

For now I think I would like to keep dbase-rs as purely a lib. 
Although in the future having a dbase CLI could make sense, its just that people would need to clone this repo in order to compile and use it.

And that means we would need to provide a CLI that is somewhat complete, something that allows to read, write, modify, convert to other format (maybe convert from other format but it might harder to have a nice CLI for that).
